/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jeanboy_demo_jnitest_NdkTest */

#ifndef _Included_com_jeanboy_demo_jnitest_NdkTest
#define _Included_com_jeanboy_demo_jnitest_NdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jeanboy_demo_jnitest_NdkTest
 * Method:    getMsg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_meigsmart_testjni_MainActivity_getMsg
  (JNIEnv *, jclass);

/*
 * Class:     com_jeanboy_demo_jnitest_NdkTest
 * Method:    onIncommingCall
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_meigsmart_testjni_MainActivity_onIncommingCall
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_jeanboy_demo_jnitest_NdkTest
 * Method:    onAccept
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_meigsmart_testjni_MainActivity_onAccept
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jeanboy_demo_jnitest_NdkTest
 * Method:    onHangup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_meigsmart_testjni_MainActivity_onHangup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
